server:
  port: 8080
spring:
  profiles:
    active: pro
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss #如果使用字符串表示，用这行设置格式
    timezone: GMT+8
    serialization:
      write-dates-as-timestamps: false #使用时间戳，使用数值timestamp表示日期
jwt:
  header: Authorization
  secret: mySecret
  expiration: 3600
  token-head: Bearer
