### 登录
POST http://localhost:8080/auth
Content-Type: application/json

{
  "username": "lhj",
  "password": "123456"
}

### 获取登录信息
GET http://localhost:8080/auth/info
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJsaGoiLCJjcmVhdGVkIjoxNTY0NjUzMzU2NDI0LCJleHAiOjE1Nzc2MTMzNTZ9.yM3cMmjzI3PDFTzyrqp2NzNO5Z2V1Y55zV-5Qlpd02HKoog1Q462VLoilbQAL7gmvELstvOn6CNtlbINopBavA

###

